"""created progressions table

Revision ID: 617cafd674c9
Revises: c000bbab939e
Create Date: 2019-09-06 17:23:47.712551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '617cafd674c9'
down_revision = 'c000bbab939e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('progressions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('progression', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('progressions')
    # ### end Alembic commands ###
