"""testing chord model update

Revision ID: 79e5da4cbfe0
Revises: 617cafd674c9
Create Date: 2020-01-21 16:23:22.835006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79e5da4cbfe0'
down_revision = '617cafd674c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chords', sa.Column('testing', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chords', 'testing')
    # ### end Alembic commands ###
