"""created chord table

Revision ID: c000bbab939e
Revises: 
Create Date: 2019-09-05 23:22:41.007438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c000bbab939e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('steps', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chords')
    # ### end Alembic commands ###
