"""added columns to chords for each key signature

Revision ID: da18277898be
Revises: 79e5da4cbfe0
Create Date: 2020-01-21 16:49:56.560876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da18277898be'
down_revision = '79e5da4cbfe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chords', sa.Column('sig_a', sa.Text(), nullable=True))
    op.add_column('chords', sa.Column('sig_a_flat', sa.Text(), nullable=True))
    op.add_column('chords', sa.Column('sig_b', sa.Text(), nullable=True))
    op.add_column('chords', sa.Column('sig_b_flat', sa.Text(), nullable=True))
    op.add_column('chords', sa.Column('sig_c', sa.Text(), nullable=True))
    op.add_column('chords', sa.Column('sig_c_sharp', sa.Text(), nullable=True))
    op.add_column('chords', sa.Column('sig_d', sa.Text(), nullable=True))
    op.add_column('chords', sa.Column('sig_d_flat', sa.Text(), nullable=True))
    op.add_column('chords', sa.Column('sig_e', sa.Text(), nullable=True))
    op.add_column('chords', sa.Column('sig_e_flat', sa.Text(), nullable=True))
    op.add_column('chords', sa.Column('sig_f', sa.Text(), nullable=True))
    op.add_column('chords', sa.Column('sig_f_sharp', sa.Text(), nullable=True))
    op.add_column('chords', sa.Column('sig_g', sa.Text(), nullable=True))
    op.add_column('chords', sa.Column('sig_g_flat', sa.Text(), nullable=True))
    op.drop_column('chords', 'testing')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chords', sa.Column('testing', sa.TEXT(), nullable=True))
    op.drop_column('chords', 'sig_g_flat')
    op.drop_column('chords', 'sig_g')
    op.drop_column('chords', 'sig_f_sharp')
    op.drop_column('chords', 'sig_f')
    op.drop_column('chords', 'sig_e_flat')
    op.drop_column('chords', 'sig_e')
    op.drop_column('chords', 'sig_d_flat')
    op.drop_column('chords', 'sig_d')
    op.drop_column('chords', 'sig_c_sharp')
    op.drop_column('chords', 'sig_c')
    op.drop_column('chords', 'sig_b_flat')
    op.drop_column('chords', 'sig_b')
    op.drop_column('chords', 'sig_a_flat')
    op.drop_column('chords', 'sig_a')
    # ### end Alembic commands ###
